### PR TITLE
EdnError 1.0.0 (std) pub API

### PR DESCRIPTION
**Pull request by Grinkers**
Draft so we can bikeshed https://github.com/naomijub/edn-rs/issues/119

### CODE REVIEW

**Comment by Grinkers** [comment]
@naomijub Can we have branches allow --force? Just tried rebasing to keep things clean/linear
```
remote: error: GH013: Repository rule violations found for refs/heads/pub-api.        
remote: Review all repository rules at http://github.com/naomijub/edn-rs/rules?ref=refs%2Fheads%2Fpub-api        
remote: 
remote: - Cannot force-push to this branch        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
To github.com:naomijub/edn-rs.git
 ! [remote rejected] pub-api -> pub-api (push declined due to repository rule violations)
error: failed to push some refs to 'github.com:naomijub/edn-rs.git'
```

**Comment by naomijub** [comment]
Will fix that once I get home

**Comment by naomijub** [comment]
Sorry I took this long, did not see the notification

**Comment by Grinkers** [comment]
Continuation from https://github.com/naomijub/edn-rs/pull/108

@naomijub Any result of namespaced maps? If not I think I'll remove `NamespacedMap`? I can't find any references.

**Comment by naomijub** [comment]
Do we not plan to support anything like ::namespace{:key "value}?

**Comment by Grinkers** [comment]
> Do we not plan to support anything like ::namespace{:key "value}?

As far as I am aware, this is not valid EDN?

**Comment by naomijub** [comment]
Weird that works in clojure. What about feature it?

**Comment by Grinkers** [comment]
I'm going through tests now, to try and decouple integration tests vs unit tests. Especially for feature organization and ability to change internal structure without everything blowing up.

Here's a couple discrepancies I've found so far, with tags and NamespaceMaps

```
(clojure.edn/read-string "#domain/model (1 2 3)")
java.lang.RuntimeException: No reader function for tag domain/model [at <repl>:1:1]

(clojure.edn/read-string "{:key \"value\"}")
{:key "value"}

(clojure.edn/read-string "::namespace{:key \"value\"}")
java.lang.RuntimeException: Invalid token: ::namespace [at <repl>:5:1]

(clojure.edn/read-string "::namespace {:key \"value\"}")
java.lang.RuntimeException: Invalid token: ::namespace [at <repl>:6:1]
```

I'm not nearly as familiar with clojure as rust or other low level stuff, so maybe I'm missing something.

**Comment by Grinkers** [comment]
Still can't --force push to keep things tidy. I pushed on my fork for now, but once fixed I'll force-push here and we don't lose the discussion.

https://github.com/naomijub/edn-rs/compare/master...Grinkers:edn-rs:pub-api

Everything compiles and tests pass, but there's clearly still some todo!(). Doc tests were a little weird because some of the string based errors have backticks, which throw a mess in the doc macros. Just changed it to a print using Debug. Error now doesn't have Eq or PartialEq, as users shouldn't be creating and comparing errors with no standard string formatting.

@naomijub 
I need to revert NamespacedMaps if it's a proper thing. I suspect it must be some domain-specific clojure library or custom reader? I've never seen anything like it, so I'll need references

I'm also not sure about Tagged. The use case in clojure is for user supplied reader functions, but there's no way for users to supply their own custom data readers at runtime. I suspect you probably quickly end up needing to reimplement all of clojure, reader, and macros. I think we keep the Tagged type so users can do whatever but not support the `Extensible` part of EDN. No data is lost, if rust ends up just being a transport.

**Comment by naomijub** [comment]
Push force is allowed, should be allowed in branches, not sure what has happened

**Comment by naomijub** [comment]
> I'm going through tests now, to try and decouple integration tests vs unit tests. Especially for feature organization and ability to change internal structure without everything blowing up.
> 
> Here's a couple discrepancies I've found so far, with tags and NamespaceMaps
> 
> ```
> (clojure.edn/read-string "#domain/model (1 2 3)")
> java.lang.RuntimeException: No reader function for tag domain/model [at <repl>:1:1]
> 
> (clojure.edn/read-string "{:key \"value\"}")
> {:key "value"}
> 
> (clojure.edn/read-string "::namespace{:key \"value\"}")
> java.lang.RuntimeException: Invalid token: ::namespace [at <repl>:5:1]
> 
> (clojure.edn/read-string "::namespace {:key \"value\"}")
> java.lang.RuntimeException: Invalid token: ::namespace [at <repl>:6:1]
> ```
> 
> I'm not nearly as familiar with clojure as rust or other low level stuff, so maybe I'm missing something.

I'm convinced, good to remove.

Also, ok on the tagged portion.

**Comment by Grinkers** [comment]
> Push force is allowed, should be allowed in branches, not sure what has happened

```
remote: Resolving deltas: 100% (33/33), completed with 17 local objects.        
remote: error: GH013: Repository rule violations found for refs/heads/pub-api.        
remote: Review all repository rules at http://github.com/naomijub/edn-rs/rules?ref=refs%2Fheads%2Fpub-api        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
To github.com:naomijub/edn-rs.git
 ! [remote rejected] pub-api -> pub-api (push declined due to repository rule violations)
error: failed to push some refs to 'github.com:naomijub/edn-rs.git'
```

Error is a bit different now. I think we need to allow changes not through a pull request

**Comment by naomijub** [comment]
All rulesets are disabled, we need to standardize which ruleset we want

**Comment by Grinkers** [comment]
That seemed to work. I think everything for master and nothing for branches would be nice? I don't expect a lot of conflicting stuff. Or I can just keep my mess elsewhere.

Still todo!()s as mentioned before. However take a look at `cargo doc` and see if the high level view of the public api seems good. Error is the biggest change. Followed by json_to_edn, and then removed things.

I still consider this a draft, but it's getting close for bundling up breaking changes.

**Comment by naomijub** [comment]
Tomorrow I might have some time to review. @evaporei can you help as well?

**Comment by Grinkers** [comment]
> Also, ok on the tagged portion.

On second thought, I think we keep the tagged type so no data is lost, but remove `Uuid` and and `Inst`. Users can match against the tagged type and do what they need to do. Right now it's not correct and I don't think we want to add the dependencies to make it correct.

```
(clojure.edn/read-string "#uuid \"af6d8699---f442-4dfd-8b26-37d80543186b\"")
java.lang.IllegalArgumentException: UUID string too large [at <repl>:1:1]

(clojure.edn/read-string "#inst \"2020lolfoobar-07-16T21:53:14.628-00:00\"")
java.lang.RuntimeException: Unrecognized date/time syntax: 2020lolfoobar-07-16T21:53:14.628-00:00 [at <repl>:4:1]
```

We just parse the string, without failure. We can add it back in when/if something like uuid and chrono get into rust std or as an optional feature if there's demand.

**Comment by Grinkers** [comment]
Renamed this draft to be for the EdnError rework. I'll start breaking things apart so it's easier to review/track. I'll rebase cleanly before this leaves being draft.

**Comment by Grinkers** [comment]
Closing due to discussion and commits being all over the place. Creating a new separate branch/PR to match the issue #119.

**Comment by evaporei** [comment]
Sorry I was away for a bit, I can definitely help with the review @naomijub

**Comment by Grinkers** [comment]
> Sorry I was away for a bit, I can definitely help with the review @naomijub

#121 and #122 are the cleaned up versions. #123 hopefully concluding all the breaking api changes

**Pull request closed without merging**
